from app.handlers import base
from app.handlers import bot_analytics
from app.handlers import bot_game
from app.handlers import broadcast
from app.handlers import game
from app.handlers import matchmaking
from app.handlers import records
from app.handlers import register
from app.handlers import stats
